Project 3: Cloning "NewsWeek" website using BootStrap.
FdI96/Bootstrap-Project pull request #1
Opened 2020-12-17 00:28 UTC by FdI96

Kindly request a code review, don't hesitate to mark any change that We have to make or something that's is wrong. I thank you in advance

Best regards.

2020-12-17 12:08 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 
Hello, @FdI96 and @widzthedvloper this is good progress. Your project requires a bit of work but you have done a good job so far. Kindly fix the following:

### DESKTOP VIEW:

- [x] At the top bar your items are not well aligned. Kindly compare them with the actual news website and you can tell there are some alignment issues. Kindly check out this [link](https://getbootstrap.com/docs/4.0/utilities/flex/) to learn more on bootstrap alignment.
  **yours**
![menu yours](https://user-images.githubusercontent.com/32361963/102484596-8c0ed400-4077-11eb-88b2-b2a87a747494.jpg)
 **original**
![menu original](https://user-images.githubusercontent.com/32361963/102484694-af398380-4077-11eb-8f74-e1a47f022b34.jpg)

- [x] Your main navigation bar does not resemble the original. Kindly fix this
   **yours**
![main nav yours](https://user-images.githubusercontent.com/32361963/102484939-017aa480-4078-11eb-9c17-057d0a6c3e70.jpg)
**original**
![main nav original](https://user-images.githubusercontent.com/32361963/102485117-38e95100-4078-11eb-81f0-fbe2daf51eb0.jpg)

- [x]  You don't have a featured slideshows section. Kindly add this section to your webpage.
     
![featured](https://user-images.githubusercontent.com/32361963/102485661-f5431700-4078-11eb-83ba-28c03d4d589f.jpg)

### MOBILE VIEW

- [x] Your mobile view is perfect. Good work on this. However, just as stated above remember to add the featured-slide section

### if you have any question kindly reach me on slack @peterrobert

### HAPPY CODING 💻

2020-12-17 18:53 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @FdI96 and @widzthedvloper  ! 👋 👋 

### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**General**
- [x] Your project looks great. However, your project cannot be approved until you write a descriptive PR Message. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.


**Recommended**

- [ ] On desktop screens, your page is taking the full width of the screen, refer to the actual site for more clarity.
- [x] Fix your navigation bar to look as similar as possible to the actual site's.
- [x] Your vertical scroll is missing on the page, making it compulsory to navigate the page by the arrow keys, please inspect this issue.
- [x] The more stories sections is stuck under the next section please review this.

**Your clone**
![Screenshot (159)](https://user-images.githubusercontent.com/49621279/102529813-baed7000-40a0-11eb-8d38-d8b17b0c432b.png)

- [x] Fix the following sections and refer to the [Newsweek](newsweek.com) site for more clarity: 
- In the Magazine
- Editor's Picks
- The section before the footer
- The footer


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-12-17 23:16 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @FdI96 and @widzthedvloper 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Please implement the suggestions as previous TSEs suggested
- [ ] Remove inline styles from HTML file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [ ] Please add the description in the `alt` attribute. (See inline comment)

### Navbar
- [ ] Please fix the issues for the navbar as previous TSEs has mentioned. You can visit [Newsweek](https://www.newsweek.com/)

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/FdI96/Bootstrap-Project/08ef5540331d1b56ecf4699941a1f72ce39a98a2/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/102545527-30286780-40d8-11eb-849a-d1c4dcd4e391.png)|![clone](https://user-images.githubusercontent.com/29689273/102545538-31599480-40d8-11eb-93e5-cf1b80ff92d8.png)|

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-12-17 23:16 UTC, umairarshadbutt commented on index.html
> +                            <img class="d-none d-lg-inline mb-2" src="images/nav-big-logo.png" alt="">
Please add the description for the alt attribute

2020-12-17 23:16 UTC, umairarshadbutt commented on index.html
> +                            <img class="h-100 d-lg-none" src="images/navbar/hamburger.png" alt="">
Please add the description for the alt attribute

2020-12-17 23:16 UTC, umairarshadbutt commented on index.html
> +                                    <img style="width: 100%;" src="images/topstory/topstoryimg.webp" alt="joebiden">
Please remove the inline style

2020-12-17 23:16 UTC, umairarshadbutt commented on index.html
> +                                        <img style="width: 100%;" src="images/topstory/topstoryimg.webp" alt="joebiden">
Please remove the inline style

2020-12-17 23:16 UTC, umairarshadbutt commented on index.html
> +                    <p class="align-self-md-end mb-md-0" style="font-size: 12px;">© 2020 NEWSWEEK DIGITAL LLC</p>
Please remove the inline style

2020-12-18 00:00 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2020-12-18 00:35 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @FdI96 and @widzthedvloper  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Fix the logo in navbar on mobile screen, it is very small compared to the original
- [ ] And reduce the space which is on the right most of the navbar, between the hamburger bars and the screen edge (on the right side) 

| Your clone | Original page |
| --- | --- |
|![Screenshot from 2020-12-18 02-21-30](https://user-images.githubusercontent.com/56886064/102559130-cf992a80-40d7-11eb-8934-5313c43020b7.png)|![Screenshot from 2020-12-18 02-22-15](https://user-images.githubusercontent.com/56886064/102559172-e475be00-40d7-11eb-8fe7-501c10fae32c.png)|

This screenshot is taken on screens <550px

:point_right: Could you see the difference :question: :question: :question: 

- [x] Images in the opinion section are strecthed, fix that issue

| Your clone | Original page |
| --- | --- |
|![Screenshot from 2020-12-18 02-27-42](https://user-images.githubusercontent.com/56886064/102559477-a5943800-40d8-11eb-839c-dfbf93f2a8c7.png) |![Screenshot from 2020-12-18 02-28-12](https://user-images.githubusercontent.com/56886064/102559507-b5138100-40d8-11eb-98f3-529028127c1f.png) |

:point_right: Could you see the difference :question: :question: :question: 

- [x] Fix the Signup form, on mobile screens

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-12-18 02-29-34](https://user-images.githubusercontent.com/56886064/102559632-fad04980-40d8-11eb-83ce-1d3ff0c167a6.png) | ![Screenshot from 2020-12-18 02-30-39](https://user-images.githubusercontent.com/56886064/102559658-0d4a8300-40d9-11eb-8cce-f2fd65d97814.png) |

:point_right: Could you see the difference :question: :question: :question: 

- [x] Fix the news letter section on mobile screens

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-12-18 02-32-55](https://user-images.githubusercontent.com/56886064/102559792-61556780-40d9-11eb-974a-a55dc26d3682.png) | ![Screenshot from 2020-12-18 02-33-59](https://user-images.githubusercontent.com/56886064/102559856-82b65380-40d9-11eb-9561-0bf423141bcc.png)|

:point_right: Could you see the difference :question: :question: :question: 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2020-12-18 02:31 UTC, mimipeshy commented
## STATUS: APPROVED

Hey team 👋 👋 , great job on working on all required changes, this project is therefore approved. Go ahead and merge 😄 
All the best in the next projects. Happy Coding 💻 

[OPTIONAL]

- [ ] Images in the opinion section are stretched, fix that issue 

Regards
Peris Ndanu

2020-12-18 14:19 UTC, merged